INSERT INTO planets (id, name, type, mass, diameter, distance) VALUES (1, 'Mercury', 'Terrestrial', 0.33011, 4879, 0.39);
INSERT INTO planets (id, name, type, mass, diameter, distance) VALUES (2, 'Venus', 'Terrestrial', 4.8675, 12104, 0.72);
INSERT INTO planets (id, name, type, mass, diameter, distance) VALUES (3, 'Earth', 'Terrestrial', 5.97237, 12756, 1.00);
INSERT INTO planets (id, name, type, mass, diameter, distance) VALUES (4, 'Mars', 'Terrestrial', 0.64171, 6792, 1.52);
INSERT INTO planets (id, name, type, mass, diameter, distance) VALUES (5, 'Jupiter', 'Gas Giant', 1898.19, 142984, 5.20);
INSERT INTO planets (id, name, type, mass, diameter, distance) VALUES (6, 'Saturn', 'Gas Giant', 568.34, 120536, 9.54);
INSERT INTO planets (id, name, type, mass, diameter, distance) VALUES (7, 'Uranus', 'Ice Giant', 86.813, 51118, 19.22);
INSERT INTO planets (id, name, type, mass, diameter, distance) VALUES (8, 'Neptune', 'Ice Giant', 102.413, 49528, 30.11);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (1, 3, 'Moon', 3474);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (2, 4, 'Phobos', 22);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (3, 4, 'Deimos', 12);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (4, 5, 'Io', 3643);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (5, 5, 'Europa', 3122);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (6, 5, 'Ganymede', 5262);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (7, 5, 'Callisto', 4821);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (8, 6, 'Mimas', 396);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (9, 6, 'Enceladus', 504);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (10, 6, 'Tethys', 1062);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (11, 6, 'Dione', 1120);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (12, 6, 'Rhea', 1528);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (13, 6, 'Titan', 5152);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (14, 6, 'Hyperion', 270);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (15, 6, 'Iapetus', 1436);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (16, 7, 'Miranda', 471);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (17, 7, 'Ariel', 1157);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (18, 7, 'Umbriel', 1169);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (19, 7, 'Titania', 1577);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (20, 7, 'Oberon', 1522);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (21, 8, 'Triton', 2707);
INSERT INTO moons (id, planet_id, name, diameter) VALUES (22, 8, 'Nereid', 340);